# Используем официальный Node.js образ
FROM node:18

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем оставшиеся файлы
COPY . .

# Указываем порт, который будет слушать приложение
EXPOSE 8081

# Команда запуска
CMD ["node", "index.js"]